export const initialWorkspaces = [
  {
    id: "ws-prod",
    name: "Acme Corporation",
    environment: "Production",
    active: true,
  },
  {
    id: "ws-stage",
    name: "Acme Staging",
    environment: "Staging",
    active: false,
  },
  {
    id: "ws-dev",
    name: "Acme Labs",
    environment: "Development",
    active: false,
  },
];

export const initialProjects = [
  {
    id: "proj-customer",
    name: "Customer Platform",
    slug: "customer-platform",
    description:
      "Core customer records, billing profiles, and authentication migration pipeline.",
    environment: "Production",
    migrationCount: 4,
    agentCount: 2,
    lastActivity: "4 minutes ago",
    status: "ACTIVE",
    createdAt: "2025-01-15T08:30:00Z",
  },
  {
    id: "proj-analytics",
    name: "Analytics Pipeline",
    slug: "analytics-pipeline",
    description:
      "High-throughput event streaming and analytics warehouse synchronization.",
    environment: "Production",
    migrationCount: 3,
    agentCount: 2,
    lastActivity: "2 hours ago",
    status: "ACTIVE",
    createdAt: "2025-01-20T10:15:00Z",
  },
  {
    id: "proj-commerce",
    name: "Commerce Migration",
    slug: "commerce-migration",
    description:
      "Legacy MySQL product catalog and orders transition to distributed PostgreSQL.",
    environment: "Staging",
    migrationCount: 2,
    agentCount: 1,
    lastActivity: "Yesterday",
    status: "ACTIVE",
    createdAt: "2025-02-01T14:22:00Z",
  },
  {
    id: "proj-archive",
    name: "Cold Storage Archive",
    slug: "cold-storage-archive",
    description:
      "Batch export of historical compliance records to customer-owned S3 buckets.",
    environment: "Production",
    migrationCount: 1,
    agentCount: 1,
    lastActivity: "3 days ago",
    status: "IDLE",
    createdAt: "2025-02-10T16:40:00Z",
  },
];

export const initialAgents = [
  {
    id: "agent-prod-01",
    name: "Production Agent US-East",
    status: "ONLINE",
    version: "v1.4.2",
    environment: "Production",
    host: "prod-migration-01.internal",
    ip: "10.240.12.84",
    lastHeartbeat: "6 seconds ago",
    lastHeartbeatMs: 6000,
    activeMigrations: 2,
    totalCompleted: 48,
    uptime: "99.98% (42 days)",
    cpuUsage: "18%",
    memUsage: "1.4 GB / 8 GB",
    networkEgress: "48.2 MB/s",
    dockerImage: "dataforge/migration-agent:v1.4.2",
    registeredAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "agent-prod-eu",
    name: "EU Production Agent",
    status: "ONLINE",
    version: "v1.4.2",
    environment: "Production",
    host: "eu-worker-c1.internal",
    ip: "10.160.4.11",
    lastHeartbeat: "12 seconds ago",
    lastHeartbeatMs: 12000,
    activeMigrations: 1,
    totalCompleted: 31,
    uptime: "99.95% (28 days)",
    cpuUsage: "26%",
    memUsage: "2.1 GB / 8 GB",
    networkEgress: "32.6 MB/s",
    dockerImage: "dataforge/migration-agent:v1.4.2",
    registeredAt: "2025-01-18T14:15:00Z",
  },
  {
    id: "agent-stage-01",
    name: "Staging Agent",
    status: "ONLINE",
    version: "v1.4.1",
    environment: "Staging",
    host: "stage-mig-box-02.internal",
    ip: "10.120.8.99",
    lastHeartbeat: "18 seconds ago",
    lastHeartbeatMs: 18000,
    activeMigrations: 0,
    totalCompleted: 19,
    uptime: "99.82% (14 days)",
    cpuUsage: "4%",
    memUsage: "620 MB / 4 GB",
    networkEgress: "0.1 MB/s",
    dockerImage: "dataforge/migration-agent:v1.4.1",
    registeredAt: "2025-02-02T11:20:00Z",
  },
  {
    id: "agent-analytics-01",
    name: "Analytics Worker Agent",
    status: "ONLINE",
    version: "v1.4.2",
    environment: "Production",
    host: "analytics-agent-pod-7.internal",
    ip: "10.240.18.52",
    lastHeartbeat: "4 seconds ago",
    lastHeartbeatMs: 4000,
    activeMigrations: 0,
    totalCompleted: 24,
    uptime: "99.99% (50 days)",
    cpuUsage: "9%",
    memUsage: "1.1 GB / 8 GB",
    networkEgress: "1.2 MB/s",
    dockerImage: "dataforge/migration-agent:v1.4.2",
    registeredAt: "2025-01-22T17:00:00Z",
  },
  {
    id: "agent-legacy-01",
    name: "Legacy MySQL Relay",
    status: "OFFLINE",
    version: "v1.2.0",
    environment: "Production",
    host: "legacy-srv-datacenter3.internal",
    ip: "192.168.10.4",
    lastHeartbeat: "3 hours ago",
    lastHeartbeatMs: 10800000,
    activeMigrations: 0,
    totalCompleted: 6,
    uptime: "Degraded",
    cpuUsage: "0%",
    memUsage: "0 MB",
    networkEgress: "0 MB/s",
    dockerImage: "dataforge/migration-agent:v1.2.0",
    registeredAt: "2024-11-05T08:30:00Z",
  },
];

export const initialConnections = [
  {
    id: "conn-pg-prod",
    name: "Production PostgreSQL",
    type: "PostgreSQL",
    status: "HEALTHY",
    host: "db-primary.internal.company",
    port: 5432,
    database: "production",
    schema: "public",
    tables: ["customers", "users", "auth_tokens", "audit_logs"],
    lastTested: "4 minutes ago",
    latencyMs: 1.8,
    managedBy: "Customer Vault / AWS Secrets Manager",
    environment: "Production",
  },
  {
    id: "conn-pg-analytics",
    name: "Analytics Warehouse PostgreSQL",
    type: "PostgreSQL",
    status: "HEALTHY",
    host: "analytics-dw.internal.company",
    port: 5432,
    database: "analytics",
    schema: "public",
    tables: ["customers_v2", "dim_users", "fact_orders", "event_logs"],
    lastTested: "12 minutes ago",
    latencyMs: 3.2,
    managedBy: "Customer Vault / AWS Secrets Manager",
    environment: "Production",
  },
  {
    id: "conn-mysql-legacy",
    name: "Commerce Legacy MySQL",
    type: "MySQL",
    status: "HEALTHY",
    host: "mysql-cluster.internal.company",
    port: 3306,
    database: "ecommerce_legacy",
    schema: "ecommerce",
    tables: ["orders", "order_items", "catalog_products", "inventory"],
    lastTested: "31 minutes ago",
    latencyMs: 4.1,
    managedBy: "Customer Vault / AWS Secrets Manager",
    environment: "Staging",
  },
  {
    id: "conn-s3-lake",
    name: "Data Lake S3 Bucket",
    type: "S3",
    status: "HEALTHY",
    host: "s3.us-east-1.amazonaws.com",
    bucket: "company-compliance-archive-prod",
    pathPrefix: "exports/v2025/",
    lastTested: "1 hour ago",
    latencyMs: 24.5,
    managedBy: "IAM Role ARN (VPC-Assumed)",
    environment: "Production",
  },
  {
    id: "conn-csv-internal",
    name: "Agent Local Mount CSV",
    type: "CSV",
    status: "HEALTHY",
    filePath: "/var/data/exports/customers_dump.csv",
    delimiter: ",",
    encoding: "UTF-8",
    lastTested: "2 hours ago",
    latencyMs: 0.4,
    managedBy: "Agent Container Filesystem Mount",
    environment: "Production",
  },
];

export const initialMigrations = [
  {
    id: "mig-customers",
    name: "Customer Data Migration",
    projectId: "proj-customer",
    projectName: "Customer Platform",
    sourceConnId: "conn-pg-prod",
    sourceType: "PostgreSQL",
    sourceTargetLabel: "production.customers → analytics.customers_v2",
    targetConnId: "conn-pg-analytics",
    targetType: "PostgreSQL",
    agentId: "agent-prod-01",
    agentName: "Production Agent US-East",
    status: "RUNNING",
    progress: 78.2,
    recordsProcessed: 782400,
    recordsTotal: 1000000,
    recordsSucceeded: 780912,
    recordsFailed: 1488,
    throughput: 696,
    startedAt: "10:42 AM Today",
    elapsed: "18m 42s",
    eta: "5m 12s",
    checkpoint: "chkpt_b294_offset_782000",
    retries: 4,
    batchSize: 2000,
    fieldMappingsCount: 6,
    lastRun: "2 minutes ago",
  },
  {
    id: "mig-orders",
    name: "Commerce Orders Pipeline",
    projectId: "proj-commerce",
    projectName: "Commerce Migration",
    sourceConnId: "conn-mysql-legacy",
    sourceType: "MySQL",
    sourceTargetLabel: "ecommerce.orders → analytics.fact_orders",
    targetConnId: "conn-pg-analytics",
    targetType: "PostgreSQL",
    agentId: "agent-prod-01",
    agentName: "Production Agent US-East",
    status: "COMPLETED",
    progress: 100,
    recordsProcessed: 2450000,
    recordsTotal: 2450000,
    recordsSucceeded: 2449880,
    recordsFailed: 120,
    throughput: 0,
    startedAt: "Yesterday 04:00 PM",
    elapsed: "54m 10s",
    eta: "Finished",
    checkpoint: "completed_final",
    retries: 2,
    batchSize: 5000,
    fieldMappingsCount: 9,
    lastRun: "Yesterday",
  },
  {
    id: "mig-analytics-sync",
    name: "User Event Sync",
    projectId: "proj-analytics",
    projectName: "Analytics Pipeline",
    sourceConnId: "conn-pg-prod",
    sourceType: "PostgreSQL",
    sourceTargetLabel: "production.audit_logs → analytics.event_logs",
    targetConnId: "conn-pg-analytics",
    targetType: "PostgreSQL",
    agentId: "agent-prod-eu",
    agentName: "EU Production Agent",
    status: "PAUSED",
    progress: 45.0,
    recordsProcessed: 450000,
    recordsTotal: 1000000,
    recordsSucceeded: 449600,
    recordsFailed: 400,
    throughput: 0,
    startedAt: "08:15 AM Today",
    elapsed: "12m 14s",
    eta: "Paused",
    checkpoint: "chkpt_b180_offset_450000",
    retries: 0,
    batchSize: 2500,
    fieldMappingsCount: 5,
    lastRun: "1 hour ago",
  },
  {
    id: "mig-legacy-import",
    name: "Legacy CSV Archive Import",
    projectId: "proj-customer",
    projectName: "Customer Platform",
    sourceConnId: "conn-csv-internal",
    sourceType: "CSV",
    sourceTargetLabel: "customers_dump.csv → production.users",
    targetConnId: "conn-pg-prod",
    targetType: "PostgreSQL",
    agentId: "agent-stage-01",
    agentName: "Staging Agent",
    status: "FAILED",
    progress: 42.1,
    recordsProcessed: 210500,
    recordsTotal: 500000,
    recordsSucceeded: 206100,
    recordsFailed: 4400,
    throughput: 0,
    startedAt: "3 hours ago",
    elapsed: "6m 28s",
    eta: "Halted",
    checkpoint: "chkpt_error_b84_null_constraint",
    retries: 5,
    batchSize: 2000,
    fieldMappingsCount: 8,
    lastRun: "3 hours ago",
  },
  {
    id: "mig-compliance-export",
    name: "S3 Compliance Batch Dump",
    projectId: "proj-archive",
    projectName: "Cold Storage Archive",
    sourceConnId: "conn-pg-prod",
    sourceType: "PostgreSQL",
    sourceTargetLabel: "production.audit_logs → s3://exports/v2025/",
    targetConnId: "conn-s3-lake",
    targetType: "S3",
    agentId: "agent-prod-01",
    agentName: "Production Agent US-East",
    status: "QUEUED",
    progress: 0,
    recordsProcessed: 0,
    recordsTotal: 870000,
    recordsSucceeded: 0,
    recordsFailed: 0,
    throughput: 0,
    startedAt: "Scheduled for 11:00 PM",
    elapsed: "--",
    eta: "Scheduled",
    checkpoint: "unstarted",
    retries: 0,
    batchSize: 5000,
    fieldMappingsCount: 4,
    lastRun: "Never",
  },
];

export const initialFieldMappings = [
  {
    id: "m1",
    sourceField: "customer_id",
    targetField: "id",
    transformation: "None",
    required: true,
    type: "UUID",
  },
  {
    id: "m2",
    sourceField: "first_name",
    targetField: "first_name",
    transformation: "trim()",
    required: true,
    type: "VARCHAR(128)",
  },
  // { id: 'm3', sourceField: 'last_name', targetField: 'last_name', transformation: 'trim()', required: true, type: 'VARCHAR(128)' },
  // { id: 'm4', sourceField: 'email', targetField: 'email', transformation: 'lowercase()', required: true, type: 'VARCHAR(255)' },
  // { id: 'm5', sourceField: 'phone', targetField: 'phone_number', transformation: 'normalizePhone()', required: false, type: 'VARCHAR(32)' },
  // { id: 'm6', sourceField: 'created_at', targetField: 'created_at', transformation: 'toDate(ISO8601)', required: true, type: 'TIMESTAMPTZ' },
];

export const initialActivities = [
  {
    id: "act-1",
    type: "MIGRATION_COMPLETED",
    title: "Migration completed",
    detail: "Commerce Orders Pipeline reached 100% (2.45M records)",
    timestamp: "2 minutes ago",
    user: "System Automation",
    icon: "check",
    severity: "success",
  },
  {
    id: "act-2",
    type: "AGENT_CONNECTED",
    title: "Agent heartbeat verified",
    detail: "Production Agent US-East connected from 10.240.12.84",
    timestamp: "8 minutes ago",
    user: "Production Agent",
    icon: "server",
    severity: "info",
  },
  {
    id: "act-3",
    type: "MIGRATION_STARTED",
    title: "Migration started",
    detail: "Customer Data Migration resumed by Abdul Moeez",
    timestamp: "14 minutes ago",
    user: "Abdul Moeez",
    icon: "play",
    severity: "active",
  },
  {
    id: "act-4",
    type: "CONNECTION_TEST_FAILED",
    title: "Connection warning flagged",
    detail: "Legacy MySQL latency spiked to 210ms during routine health probe",
    timestamp: "31 minutes ago",
    user: "Health Monitor",
    icon: "alert",
    severity: "warning",
  },
  {
    id: "act-5",
    type: "FIELD_MAPPING_UPDATED",
    title: "Schema mapping updated",
    detail: "Added transformation normalizePhone() to Customer Platform",
    timestamp: "1 hour ago",
    user: "Sarah Khan",
    icon: "code",
    severity: "info",
  },
  {
    id: "act-6",
    type: "AGENT_ENROLLED",
    title: "New agent registered",
    detail: "EU Production Agent successfully enrolled in Production",
    timestamp: "Yesterday",
    user: "Abdul Moeez",
    icon: "shield",
    severity: "success",
  },
];

export const initialLogs = [
  {
    id: "l1",
    time: "10:42:31.102",
    level: "INFO",
    source: "Agent US-East",
    message: "Migration session initiated with token auth",
  },
  {
    id: "l2",
    time: "10:42:32.418",
    level: "INFO",
    source: "Agent US-East",
    message:
      "Connected to source PostgreSQL pool (db-primary.internal.company:5432)",
  },
  {
    id: "l3",
    time: "10:42:33.891",
    level: "INFO",
    source: "Agent US-East",
    message:
      "Connected to target PostgreSQL pool (analytics-dw.internal.company:5432)",
  },
  {
    id: "l4",
    time: "10:42:35.004",
    level: "INFO",
    source: "Agent US-East",
    message: "Discovered 1,000,000 source records in public.customers",
  },
  {
    id: "l5",
    time: "10:42:41.229",
    level: "INFO",
    source: "Engine",
    message: "Processing batch 1 (records 1 - 2000) · Throughput 710 rec/s",
  },
  {
    id: "l6",
    time: "10:42:45.890",
    level: "INFO",
    source: "Engine",
    message: "Processing batch 2 (records 2001 - 4000) · Checkpoint saved",
  },
  {
    id: "l7",
    time: "10:43:01.312",
    level: "WARN",
    source: "Transformer",
    message:
      "3 records contained non-standard E.164 phone formats; applied fallback",
  },
  {
    id: "l8",
    time: "10:43:02.045",
    level: "INFO",
    source: "Engine",
    message: "Retrying batch 4 items with relaxed validation schema",
  },
  {
    id: "l9",
    time: "10:44:19.782",
    level: "INFO",
    source: "ControlPlane",
    message: "WSS heartbeat acknowledged from agent-prod-01 (latency 1.4ms)",
  },
  {
    id: "l10",
    time: "10:46:55.109",
    level: "INFO",
    source: "Engine",
    message: "Batch 142 committed to target table public.customers_v2",
  },
  {
    id: "l11",
    time: "10:48:12.441",
    level: "WARN",
    source: "Transformer",
    message:
      "Missing country_code detected on customer_id 92831 · Defaulting to +1",
  },
  {
    id: "l12",
    time: "10:50:00.001",
    level: "INFO",
    source: "Engine",
    message:
      "Throughput stabilized at 696 records/sec · Checkpoint chkpt_b294 committed",
  },
];

export const initialTeam = [
  {
    id: "u1",
    name: "Abdul Moeez",
    email: "admin@company.com",
    role: "Owner",
    avatar: "AM",
    status: "Active",
    joined: "Jan 2025",
  },
  {
    id: "u2",
    name: "Sarah Khan",
    email: "sarah@company.com",
    role: "Admin",
    avatar: "SK",
    status: "Active",
    joined: "Jan 2025",
  },
  {
    id: "u3",
    name: "Marcus Vance",
    email: "marcus@company.com",
    role: "Operator",
    avatar: "MV",
    status: "Active",
    joined: "Feb 2025",
  },
  {
    id: "u4",
    name: "Elena Rostova",
    email: "elena@company.com",
    role: "Viewer",
    avatar: "ER",
    status: "Pending Invite",
    joined: "Feb 2025",
  },
];

export const initialInvoices = [
  {
    id: "INV-2025-002",
    date: "Feb 01, 2025",
    amount: "$99.00",
    status: "Paid",
    plan: "Pro Tier",
    pdf: "#",
  },
  {
    id: "INV-2025-001",
    date: "Jan 01, 2025",
    amount: "$99.00",
    status: "Paid",
    plan: "Pro Tier",
    pdf: "#",
  },
];
